Update automate-DESDEO-emo.yml
Update loop

diff --git a/.github/workflows/automate-DESDEO-emo.yml b/.github/workflows/automate-DESDEO-emo.yml
--- a/.github/workflows/automate-DESDEO-emo.yml
+++ b/.github/workflows/automate-DESDEO-emo.yml
@@ -58,14 +58,42 @@ jobs:
         id: run-tests
         run: |
           source .venv/bin/activate
-          retries=3
-          for i in $(seq 1 $retries); do
-            pytest tests/
-            if [ $? -eq 0 ]; then
-              break
-            fi
-            echo "Retrying failed tests... (Attempt $i)"
-          done
+          retries=10
+          failed_tests=""
+
+          # Run all tests
+          pytest tests/
+          exit_code=$?
+
+          if [ $exit_code -eq 0 ]; then
+            echo "All tests passed!"
+          else
+            for i in $(seq 1 $retries); do
+              # Run only the failed tests
+              pytest $failed_tests
+              exit_code=$?
+
+              if [ $exit_code -eq 0 ]; then
+                echo "All tests passed!"
+                break  # All tests passed, exit the loop
+              fi
+
+              # Get the failed test files from the pytest output
+              failed_files=$(pytest --collect-only $failed_tests | awk '/<Module/ {print $NF}')
+
+              # Build the test file pattern for rerunning failed tests
+              test_files=""
+              for file in $failed_files; do
+                test_files+=" tests/$file"
+              done
+
+              failed_tests=$test_files
+
+              echo "Retrying failed tests... (Attempt $i)"
+            done
+          fi
+
+
       
   automerge:
     name: Auto merge after successful checks
